"""Regression tests for the 0.11.0 context-compaction fixes.

Five separate bugs in `open_webui/utils/context_compaction.py` (plus one in
`open_webui/utils/response.py`) all made automatic context compaction cut the
conversation in the wrong place or fire at the wrong time:

1. Turn boundaries (#27035, commits 959558f, 17e6496). `_find_compaction_boundary`
   walked the split point forward past `tool` messages and then clamped it with
   `min(split, len(messages) - 2)`, which could pull the boundary back into the
   middle of the turn it had just walked past, so an assistant `tool_calls`
   message and its `tool` result ended up on opposite sides of the summary. The
   fix picks the LAST `user` message index at or before the target instead, and
   takes a clamped `retention_percentage`.

2. Summary model on a direct connection (#26806). `_generate_summary` only ever
   resolved the generic task model, so a configured
   `chat.context_compaction.model` was ignored and the summary was generated by
   the chat's own (possibly direct-connection) model.

3. System prompt through compaction (commits 70549c5, 1568868, 44f4f9d, #26713,
   #26710). The system message was just another list element, so it was folded
   into the summary and dropped from the request. It is now hoisted out and
   re-prepended on every return path.

4. Continuity (#27037, commits 0c23466, f730733). The summary checkpoint was
   written on the CURRENT message id rather than the first RETAINED message, so
   the next turn's `_apply_latest_summary_checkpoint` sliced away the whole
   retained window. The save guard also missed the `temporary:` chat prefix and
   bumped the chat's updated_at.

5. Context size after tool calls (commits df94268, e8f2c12, #27031, #26752,
   #24410). `_exceeds_token_threshold` only recognised `input_tokens`, so Ollama
   (`prompt_eval_count`) and llama.cpp (`prompt_n`) usage blocks were invisible
   and compaction never fired; and `merge_usage` SUMMED `prompt_tokens` across a
   tool loop, so three provider calls reported 3x the real prompt size.

6. Context-usage readout (commit 7a9928ef1, #27362). `get_chat_context_usage` does
   not exist before 0.11.0 at all; it is the backend half of the compaction meter
   the composer shows. Section 5d covers it, so those three tests fail on v0.10.2
   with `AttributeError` rather than a wrong value. That is a capability gap, not a
   behavioural regression, and it is called out here so nobody mistakes it for one.

Discriminates: passes on v0.11.0 and v0.11.1, fails on v0.10.2 (boundary lands on
a `tool` message, the compaction model and the system message are dropped, the
checkpoint is written on the current message id, Ollama/llama.cpp usage is ignored
and `prompt_tokens` is summed across the tool loop).
"""

from __future__ import annotations

from types import SimpleNamespace
from unittest.mock import AsyncMock

import pytest

pytestmark = pytest.mark.regression


# -----------------------------------------------------------------------------
# Fixtures and helpers
# -----------------------------------------------------------------------------


@pytest.fixture
def compaction(owui_module):
    return owui_module("open_webui.utils.context_compaction")


@pytest.fixture
def response_utils(owui_module):
    return owui_module("open_webui.utils.response")


@pytest.fixture
def chat_utils(owui_module):
    return owui_module("open_webui.utils.chat")


def _patch_config(monkeypatch, compaction, values: dict) -> None:
    """Stub the config store, the only I/O `_load_config`/`_generate_summary` do."""

    async def fake_get_many(*keys, **_kwargs):
        return {key: values.get(key) for key in keys if key in values}

    async def fake_get(key, *_args, **_kwargs):
        return values.get(key)

    monkeypatch.setattr(compaction.Config, "get_many", fake_get_many)
    monkeypatch.setattr(compaction.Config, "get", fake_get)


def _enabled_config(**overrides) -> dict:
    values = {
        "chat.context_compaction.enable": True,
        "chat.context_compaction.token_threshold": 10,
        "chat.context_compaction.prompt_template": "",
    }
    values.update(overrides)
    return values


def _fake_request():
    return SimpleNamespace(state=SimpleNamespace())


def _completion(text: str):
    return {"choices": [{"message": {"content": text}}]}


# A user turn, then a turn whose assistant fans out into three tool results.
# Pre-fix the boundary walks past the tool block and is then clamped back onto
# the last `tool` message, orphaning it from its `tool_calls` assistant.
TOOL_LOOP_MESSAGES = [
    {"role": "user", "content": "first question"},
    {"role": "assistant", "content": "first answer"},
    {"role": "user", "content": "second question"},
    {"role": "assistant", "content": "second answer"},
    {"role": "user", "content": "third question"},
    {"role": "assistant", "content": "", "tool_calls": [{"id": "c1"}, {"id": "c2"}]},
    {"role": "tool", "content": "tool result one"},
    {"role": "tool", "content": "tool result two"},
    {"role": "tool", "content": "tool result three"},
    {"role": "assistant", "content": "third answer"},
]


# -----------------------------------------------------------------------------
# 1. Turn boundaries (narrow)
# -----------------------------------------------------------------------------


def test_boundary_lands_on_a_user_turn(compaction):
    boundary = compaction._find_compaction_boundary(list(TOOL_LOOP_MESSAGES))
    assert TOOL_LOOP_MESSAGES[boundary]["role"] == "user"


def test_boundary_does_not_orphan_a_tool_result(compaction):
    boundary = compaction._find_compaction_boundary(list(TOOL_LOOP_MESSAGES))
    retained = TOOL_LOOP_MESSAGES[boundary:]
    assert retained[0]["role"] != "tool"
    # Every retained tool result still has its tool_calls assistant retained too.
    for idx, message in enumerate(retained):
        if message["role"] == "tool":
            assert any(m.get("tool_calls") for m in retained[:idx])


def test_load_config_reads_retention_percentage(monkeypatch, compaction):
    _patch_config(
        monkeypatch,
        compaction,
        _enabled_config(**{"chat.context_compaction.retention_percentage": 25}),
    )
    config = _run(compaction._load_config())
    assert config["retention_percentage"] == 25


def test_load_config_clamps_and_defaults_retention_percentage(monkeypatch, compaction):
    for raw, expected in ((5, 10), (95, 50), ("garbage", 40), (None, 40)):
        _patch_config(
            monkeypatch,
            compaction,
            _enabled_config(**{"chat.context_compaction.retention_percentage": raw}),
        )
        assert _run(compaction._load_config())["retention_percentage"] == expected


def test_retention_percentage_moves_the_boundary(compaction):
    keep_more = compaction._find_compaction_boundary(list(TOOL_LOOP_MESSAGES), 50)
    keep_less = compaction._find_compaction_boundary(list(TOOL_LOOP_MESSAGES), 10)
    assert keep_more <= keep_less
    assert TOOL_LOOP_MESSAGES[keep_less]["role"] == "user"


# -----------------------------------------------------------------------------
# 1b. Boundary invariant across shapes (broad)
# -----------------------------------------------------------------------------


def _conversation(turns: int, tools_per_turn: int) -> list[dict]:
    messages: list[dict] = []
    for turn in range(turns):
        messages.append({"role": "user", "content": f"q{turn}"})
        if tools_per_turn:
            messages.append({"role": "assistant", "tool_calls": [{"id": f"c{turn}"}]})
            for tool in range(tools_per_turn):
                messages.append({"role": "tool", "content": f"r{turn}-{tool}"})
        messages.append({"role": "assistant", "content": f"a{turn}"})
    return messages


@pytest.mark.parametrize("turns", [2, 3, 4, 6, 9])
@pytest.mark.parametrize("tools_per_turn", [1, 3])
@pytest.mark.parametrize("retention", [None, 10, 40, 50])
def test_boundary_never_splits_a_turn(compaction, turns, tools_per_turn, retention):
    messages = _conversation(turns, tools_per_turn)
    # `retention is None` drives the default arity, which every ref accepts, so these cases
    # fail on a bad boundary rather than on the signature change.
    boundary = (
        compaction._find_compaction_boundary(messages)
        if retention is None
        else compaction._find_compaction_boundary(messages, retention)
    )
    assert 0 <= boundary < len(messages)
    if boundary:
        assert messages[boundary]["role"] == "user"
    retained = messages[boundary:]
    for idx, message in enumerate(retained):
        if message["role"] == "tool":
            assert any(m.get("tool_calls") for m in retained[:idx])


# -----------------------------------------------------------------------------
# 2. Summary model on a direct connection (narrow)
# -----------------------------------------------------------------------------


MODELS = {
    "direct-model": {"owned_by": "openai"},
    "compaction-model": {"owned_by": "openai"},
    "task-model": {"owned_by": "openai"},
}


def _generate_summary(compaction, chat_utils, monkeypatch, config_values):
    _patch_config(monkeypatch, compaction, config_values)
    captured = {}

    async def fake_generate_chat_completion(request, form_data, user, **_kwargs):
        captured["payload"] = form_data
        return _completion("a summary")

    monkeypatch.setattr(chat_utils, "generate_chat_completion", fake_generate_chat_completion)
    summary = _run(
        compaction._generate_summary(
            _fake_request(),
            None,
            "direct-model",
            MODELS,
            [{"role": "user", "content": "old"}],
            [{"role": "user", "content": "new"}],
            None,
            "",
        )
    )
    return summary, captured["payload"]


def test_configured_compaction_model_wins(compaction, chat_utils, monkeypatch):
    summary, payload = _generate_summary(
        compaction,
        chat_utils,
        monkeypatch,
        {
            "task.model.default": None,
            "task.model.external": None,
            "chat.context_compaction.model": "compaction-model",
        },
    )
    assert payload["model"] == "compaction-model"
    assert summary == "a summary"


def test_compaction_model_beats_the_generic_task_model(compaction, chat_utils, monkeypatch):
    _, payload = _generate_summary(
        compaction,
        chat_utils,
        monkeypatch,
        {
            "task.model.default": "task-model",
            "task.model.external": "task-model",
            "chat.context_compaction.model": "compaction-model",
        },
    )
    assert payload["model"] == "compaction-model"


def test_unknown_compaction_model_falls_back(compaction, chat_utils, monkeypatch):
    _, payload = _generate_summary(
        compaction,
        chat_utils,
        monkeypatch,
        {
            "task.model.default": None,
            "task.model.external": None,
            "chat.context_compaction.model": "not-a-real-model",
        },
    )
    assert payload["model"] == "direct-model"


def test_summary_marks_itself_as_a_compaction_task(compaction, chat_utils, monkeypatch):
    _, payload = _generate_summary(
        compaction,
        chat_utils,
        monkeypatch,
        {"task.model.default": None, "task.model.external": None},
    )
    assert payload["metadata"]["task"] == "context_compaction"
    assert payload["stream"] is False


# -----------------------------------------------------------------------------
# 3. System prompt survives compaction (narrow)
# -----------------------------------------------------------------------------


SYSTEM_MESSAGE = {"role": "system", "content": "you are a helpful assistant with rules"}


def _long(text: str) -> str:
    return text * 40


def _compact(compaction, chat_utils, monkeypatch, messages, metadata=None, config=None):
    _patch_config(monkeypatch, compaction, config or _enabled_config())

    async def fake_generate_chat_completion(request, form_data, user, **_kwargs):
        return _completion("SUMMARY")

    monkeypatch.setattr(chat_utils, "generate_chat_completion", fake_generate_chat_completion)
    monkeypatch.setattr(
        compaction.Chats, "upsert_message_to_chat_by_id_and_message_id", AsyncMock()
    )
    return _run(
        compaction.compact_messages_for_request(
            _fake_request(),
            None,
            messages,
            metadata if metadata is not None else {},
            "direct-model",
            MODELS,
        )
    )


def test_system_message_survives_the_compacted_path(compaction, chat_utils, monkeypatch):
    turns = [dict(m, content=_long(m["content"])) for m in _conversation(4, 0)]
    messages = [SYSTEM_MESSAGE, *turns]
    result, summary, compacted = _compact(compaction, chat_utils, monkeypatch, list(messages))
    assert compacted is True
    assert summary == "SUMMARY"
    assert result[0] == SYSTEM_MESSAGE
    assert [m for m in result[1:] if m["role"] == "system"] == []


def test_system_message_survives_a_degenerate_split(compaction, chat_utils, monkeypatch):
    # A single user turn leaves no boundary to split on.
    messages = [
        SYSTEM_MESSAGE,
        {"role": "user", "content": _long("only question ")},
        {"role": "assistant", "content": _long("part one ")},
        {"role": "assistant", "content": _long("part two ")},
        {"role": "assistant", "content": _long("part three ")},
    ]
    result, _summary, compacted = _compact(compaction, chat_utils, monkeypatch, list(messages))
    assert compacted is False
    assert result == messages


def test_compaction_disabled_returns_messages_untouched(compaction, chat_utils, monkeypatch):
    messages = [SYSTEM_MESSAGE, *_conversation(4, 0)]
    result, summary, compacted = _compact(
        compaction,
        chat_utils,
        monkeypatch,
        list(messages),
        config={"chat.context_compaction.enable": False},
    )
    assert (result, summary, compacted) == (messages, None, False)


# -----------------------------------------------------------------------------
# 4. Checkpoint continuity (narrow)
# -----------------------------------------------------------------------------


def _identified_conversation() -> list[dict]:
    return [
        {"role": "user", "content": _long("q1 "), "id": "u1"},
        {"role": "assistant", "content": _long("a1 "), "id": "a1"},
        {"role": "user", "content": _long("q2 "), "id": "u2"},
        {"role": "assistant", "content": _long("a2 "), "id": "a2"},
        {"role": "user", "content": _long("q3 "), "id": "u3"},
        {"role": "assistant", "content": _long("a3 "), "id": "a3"},
    ]


def _compact_with_upsert(compaction, chat_utils, monkeypatch, messages, metadata):
    _patch_config(monkeypatch, compaction, _enabled_config())
    upsert = AsyncMock()

    async def fake_generate_chat_completion(request, form_data, user, **_kwargs):
        return _completion("SUMMARY")

    monkeypatch.setattr(chat_utils, "generate_chat_completion", fake_generate_chat_completion)
    monkeypatch.setattr(compaction.Chats, "upsert_message_to_chat_by_id_and_message_id", upsert)
    result = _run(
        compaction.compact_messages_for_request(
            _fake_request(), None, messages, metadata, "direct-model", MODELS
        )
    )
    return result, upsert


def test_checkpoint_is_written_on_the_first_retained_message(
    compaction, chat_utils, monkeypatch
):
    messages = _identified_conversation()
    (result, _summary, compacted), upsert = _compact_with_upsert(
        compaction,
        chat_utils,
        monkeypatch,
        messages,
        {"chat_id": "chat-1", "user_message_id": "u-current"},
    )
    assert compacted is True
    upsert.assert_awaited_once()
    args, kwargs = upsert.await_args
    assert args[0] == "chat-1"
    assert args[1] == result[0]["id"]
    assert args[2] == {"contextSummary": "SUMMARY"}
    assert kwargs.get("touch") is False


def test_temporary_chat_ids_are_not_persisted(compaction, chat_utils, monkeypatch):
    for chat_id in ("temporary:abc", "local:abc", "channel:abc"):
        _result, upsert = _compact_with_upsert(
            compaction,
            chat_utils,
            monkeypatch,
            _identified_conversation(),
            {"chat_id": chat_id, "user_message_id": "u-current"},
        )
        assert upsert.await_count == 0, chat_id


def test_summary_checkpoint_round_trips_to_the_next_turn(compaction, chat_utils, monkeypatch):
    """The retained window must survive re-entry, which is what the bug broke."""
    messages = _identified_conversation()
    (result, summary, _compacted), upsert = _compact_with_upsert(
        compaction,
        chat_utils,
        monkeypatch,
        messages,
        {"chat_id": "chat-1", "user_message_id": "u-current"},
    )
    # Replay from the id production actually persisted, not from the one we wish it used.
    checkpoint_id = upsert.await_args.args[1]
    next_turn = [dict(m) for m in messages]
    for message in next_turn:
        if message["id"] == checkpoint_id:
            message["contextSummary"] = summary
    replayed, replayed_summary = compaction._apply_latest_summary_checkpoint(next_turn)
    assert replayed_summary == summary
    assert [m["id"] for m in replayed] == [m["id"] for m in result]


# -----------------------------------------------------------------------------
# 5a. Usage accounting: provider dialects (narrow)
# -----------------------------------------------------------------------------


@pytest.mark.parametrize(
    "usage",
    [
        {"prompt_eval_count": 90_000, "eval_count": 500},  # Ollama
        {"prompt_n": 90_000, "predicted_n": 500},  # llama.cpp
        {"prompt_tokens": 90_000, "completion_tokens": 500},  # OpenAI
        {"input_tokens": 90_000, "output_tokens": 500},  # already normalised
    ],
)
def test_reported_usage_trips_the_threshold(compaction, usage):
    messages = [{"role": "user", "content": "hi"}, {"role": "assistant", "usage": usage}]
    assert compaction._exceeds_token_threshold(messages, "", None, 80_000) is True


def test_usage_under_the_threshold_does_not_trip(compaction):
    messages = [
        {"role": "user", "content": "hi"},
        {"role": "assistant", "info": {"usage": {"prompt_eval_count": 100, "eval_count": 10}}},
    ]
    assert compaction._exceeds_token_threshold(messages, "", None, 80_000) is False


def test_threshold_of_zero_never_trips(compaction):
    messages = [{"role": "assistant", "usage": {"prompt_tokens": 999_999}}]
    assert compaction._exceeds_token_threshold(messages, "", None, 0) is False


def test_estimate_is_used_when_no_usage_is_reported(compaction):
    messages = [{"role": "user", "content": "x" * 8_000}]
    assert compaction._exceeds_token_threshold(messages, "", None, 100) is True
    assert compaction._exceeds_token_threshold(messages, "", None, 100_000) is False


# -----------------------------------------------------------------------------
# 5b. Usage accounting: the global cap (narrow)
# -----------------------------------------------------------------------------


def test_per_request_threshold_is_capped_by_the_global_cap(compaction):
    metadata = {"params": {"compact_token_threshold": 500_000}}
    assert compaction._resolve_token_threshold(80_000, 50_000, metadata) == 50_000


def test_absent_per_request_threshold_falls_back_and_is_capped(compaction):
    assert compaction._resolve_token_threshold(80_000, 50_000, {}) == 50_000
    assert compaction._resolve_token_threshold(80_000, 80_000, {}) == 80_000


def test_lower_per_request_threshold_still_wins(compaction):
    metadata = {"params": {"compact_token_threshold": 1_000}}
    assert compaction._resolve_token_threshold(80_000, 80_000, metadata) == 1_000


def test_load_config_defaults_token_cap_to_the_threshold(monkeypatch, compaction):
    _patch_config(
        monkeypatch,
        compaction,
        _enabled_config(**{"chat.context_compaction.token_threshold": 12_345}),
    )
    config = _run(compaction._load_config())
    assert config["token_threshold"] == 12_345
    assert config["token_cap"] == 12_345


# -----------------------------------------------------------------------------
# 5c. merge_usage no longer sums prompt_tokens across a tool loop (narrow)
# -----------------------------------------------------------------------------


def test_prompt_tokens_are_not_summed_across_a_tool_loop(response_utils):
    calls = [
        {"prompt_tokens": 100, "completion_tokens": 10, "total_tokens": 110},
        {"prompt_tokens": 150, "completion_tokens": 20, "total_tokens": 170},
        {"prompt_tokens": 200, "completion_tokens": 30, "total_tokens": 230},
    ]
    merged = {}
    for usage in calls:
        merged = response_utils.merge_usage(merged, usage)

    assert merged["prompt_tokens"] == 200
    assert merged["completion_tokens"] == 30
    assert merged["total_tokens"] == 110 + 170 + 230


def test_prompt_tokens_never_exceed_the_largest_single_call(response_utils):
    merged = {}
    for size in (1_000, 4_000, 2_500, 9_000, 3_000):
        merged = response_utils.merge_usage(
            merged, {"prompt_tokens": size, "completion_tokens": 1, "total_tokens": size + 1}
        )
    assert merged["prompt_tokens"] <= 9_000


def test_prompt_tokens_fall_back_to_input_tokens(response_utils):
    merged = response_utils.merge_usage(
        {"prompt_tokens": 100, "completion_tokens": 5, "total_tokens": 105},
        {"input_tokens": 400, "output_tokens": 9, "total_tokens": 409},
    )
    assert merged["prompt_tokens"] == 400
    assert merged["completion_tokens"] == 9


def test_merge_usage_still_accumulates_cost_and_details(response_utils):
    merged = response_utils.merge_usage(
        {"total_tokens": 10, "cost": 1.5, "prompt_tokens_details": {"cached_tokens": 2}},
        {"total_tokens": 20, "cost": 2.5, "prompt_tokens_details": {"cached_tokens": 3}},
    )
    assert merged["total_tokens"] == 30
    assert merged["cost"] == 4.0
    assert merged["prompt_tokens_details"]["cached_tokens"] == 5


# -----------------------------------------------------------------------------
# 5d. get_chat_context_usage (narrow + nearby)
# -----------------------------------------------------------------------------


def _chat(messages_map: dict | None, current_id: str | None):
    history = {"messages": messages_map or {}, "currentId": current_id}
    return SimpleNamespace(id="chat-1", chat={"history": history}, current_message_id=None)


def _linear_map(messages: list[dict]) -> tuple[dict, str]:
    messages_map = {}
    previous_id = None
    for message in messages:
        messages_map[message["id"]] = {**message, "parentId": previous_id, "childrenIds": []}
        if previous_id:
            messages_map[previous_id]["childrenIds"] = [message["id"]]
        previous_id = message["id"]
    return messages_map, previous_id


def test_context_usage_is_none_for_an_empty_chat(compaction, monkeypatch):
    monkeypatch.setattr(compaction.Chats, "get_messages_map_by_chat_id", AsyncMock(return_value={}))
    assert _run(compaction.get_chat_context_usage(_chat({}, None), "direct-model")) is None


def test_context_usage_is_none_when_compaction_is_disabled(compaction, monkeypatch):
    messages_map, current_id = _linear_map(
        [{"id": "m1", "role": "user", "content": "hello"}]
    )
    monkeypatch.setattr(
        compaction.Chats, "get_messages_map_by_chat_id", AsyncMock(return_value=messages_map)
    )
    _patch_config(monkeypatch, compaction, {"chat.context_compaction.enable": False})
    assert _run(compaction.get_chat_context_usage(_chat(messages_map, current_id), None)) is None


def test_context_usage_reports_reported_provider_tokens(compaction, monkeypatch):
    messages_map, current_id = _linear_map(
        [
            {"id": "m1", "role": "user", "content": "hello"},
            {"id": "m2", "role": "assistant", "usage": {"prompt_eval_count": 40_000}},
        ]
    )
    monkeypatch.setattr(
        compaction.Chats, "get_messages_map_by_chat_id", AsyncMock(return_value=messages_map)
    )
    _patch_config(monkeypatch, compaction, _enabled_config(
        **{"chat.context_compaction.token_threshold": 80_000}
    ))
    usage = _run(
        compaction.get_chat_context_usage(_chat(messages_map, current_id), "direct-model")
    )
    assert usage["tokens"] == 40_000
    assert usage["threshold"] == 80_000


# -----------------------------------------------------------------------------
# Nearby: helpers that were already correct
# -----------------------------------------------------------------------------


def test_system_message_survives_below_threshold(compaction, chat_utils, monkeypatch):
    messages = [SYSTEM_MESSAGE, *_conversation(3, 0)]
    result, _summary, compacted = _compact(
        compaction,
        chat_utils,
        monkeypatch,
        list(messages),
        config=_enabled_config(**{"chat.context_compaction.token_threshold": 10_000_000}),
    )
    assert compacted is False
    assert result[0] == SYSTEM_MESSAGE


def test_merge_usage_handles_empty_sides(response_utils):
    assert response_utils.merge_usage(None, None) == {}
    assert response_utils.merge_usage({"prompt_tokens": 5}, None)["prompt_tokens"] == 5
    assert response_utils.merge_usage(None, {"prompt_tokens": 5})["prompt_tokens"] == 5


def test_apply_latest_summary_checkpoint_slices_from_the_latest_summary(compaction):
    messages = [
        {"id": "m1", "role": "user"},
        {"id": "m2", "role": "assistant", "contextSummary": "older"},
        {"id": "m3", "role": "user"},
        {"id": "m4", "role": "assistant", "context_summary": "newer"},
        {"id": "m5", "role": "user"},
    ]
    sliced, summary = compaction._apply_latest_summary_checkpoint(messages)
    assert summary == "newer"
    assert [m["id"] for m in sliced] == ["m4", "m5"]


def test_apply_latest_summary_checkpoint_without_a_summary(compaction):
    messages = [{"id": "m1", "role": "user"}, {"id": "m2", "role": "assistant"}]
    assert compaction._apply_latest_summary_checkpoint(messages) == (messages, None)
    assert compaction._apply_latest_summary_checkpoint([]) == ([], None)


def test_response_text_reads_the_usual_shapes(compaction):
    assert compaction._response_text(_completion("hi")) == "hi"
    assert compaction._response_text([_completion("hi")]) == "hi"
    assert compaction._response_text({"choices": [{"message": {"reasoning_content": "r"}}]}) == "r"
    assert compaction._response_text({"output": [{"content": [{"text": "o"}]}]}) == "o"
    assert compaction._response_text(None) == ""
    assert compaction._response_text("plain") == ""


def test_token_estimates(compaction):
    assert compaction._estimate_tokens(None) == 0
    assert compaction._estimate_tokens("") == 0
    assert compaction._estimate_tokens("x" * 400) == 100
    assert compaction._estimate_messages_tokens([]) == 0
    image = [{"role": "user", "content": [{"type": "image_url", "image_url": {"url": "d"}}]}]
    assert compaction._estimate_messages_tokens(image) >= 1_000


def test_normalize_usage_maps_provider_dialects(response_utils):
    for usage in (
        {"prompt_eval_count": 7, "eval_count": 3},
        {"prompt_n": 7, "predicted_n": 3},
        {"prompt_tokens": 7, "completion_tokens": 3},
    ):
        normalized = response_utils.normalize_usage(usage)
        assert (normalized["input_tokens"], normalized["output_tokens"]) == (7, 3)
        assert normalized["total_tokens"] == 10
    assert response_utils.normalize_usage({}) == {}


# -----------------------------------------------------------------------------
# Async driver: keeps every coroutine bounded by an explicit timeout.
# -----------------------------------------------------------------------------


def _run(coroutine, timeout: float = 10.0):
    import asyncio

    async def bounded():
        return await asyncio.wait_for(coroutine, timeout)

    return asyncio.run(bounded())
