"""Journey: suggested follow-ups under a reply, generated by the task model and sent with a click.

With follow-up generation on in the admin's task settings, a finished reply asks the model for
follow-ups and lists them under the reply, where they stay after a reload. A click sends the
follow-up as the next message, or puts it in the message box when the account prefers that
(Insert Follow-Up Prompt to Input). Follow-ups show only under the last reply unless the account
keeps them, and an account that switched follow-ups off is never offered any and asks for none.

Discriminates: passes on dev 30f3f6a8f; in a backend copy that stores and sends no generated
follow-ups the generated, click, keep and insert tests fail; in a frontend build that always asks
for follow-ups the switched-off test fails, and with Insert Follow-Up Prompt to Input ignored the
insert test fails.
"""

from __future__ import annotations

import json

import pytest
from playwright.sync_api import Locator, Page, expect

from harness import upstream as reply
from utils.chat_ui import chat_input, conversation, expect_reply, last_reply, replies, send

pytestmark = [pytest.mark.journey, pytest.mark.requires_browser, pytest.mark.requires_source]

FOLLOW_UP_TASK = "relevant follow-up questions"
QUESTION = "Which grapes grow in the Douro valley?"
ANSWER = "Touriga Nacional leads the reds."
FOLLOW_UPS = ["What does Touriga Nacional taste like?", "When is the harvest?"]


@pytest.fixture
def follow_up_generation_on(admin, preserve):
    preserve("tasks")
    with admin.client() as client:
        current = client.get("/api/v1/tasks/config").json()
        saved = client.post(
            "/api/v1/tasks/config/update", json={**current, "ENABLE_FOLLOW_UP_GENERATION": True}
        )
    saved.raise_for_status()


def _account_with(make_user, **ui_settings):
    account = make_user()
    if ui_settings:
        with account.client() as client:
            saved = client.post("/api/v1/users/user/settings/update", json={"ui": ui_settings})
        assert saved.status_code == 200, saved.text
    return account


def _offer_follow_ups(upstream) -> None:
    # queued first, so the follow-up task, which quotes the question, cannot take the chat's reply
    upstream.queue(
        reply.text(json.dumps({"follow_ups": FOLLOW_UPS}), match=reply.answering(FOLLOW_UP_TASK)),
        reply.text(ANSWER, match=reply.answering(QUESTION)),
    )


def _follow_up(page: Page, text: str) -> Locator:
    return conversation(page).get_by_role("button", name=f"Follow up: {text}")


def _asked_answered(page: Page, upstream) -> None:
    _offer_follow_ups(upstream)
    send(page, QUESTION)
    expect_reply(page, ANSWER)


def test_generated_follow_ups_are_listed_under_the_reply_and_kept(
    page_for, make_user, upstream, follow_up_generation_on
):
    page = page_for(make_user())
    _asked_answered(page, upstream)

    for text in FOLLOW_UPS:
        expect(_follow_up(page, text)).to_be_visible()
    page.reload()
    expect_reply(page, ANSWER)
    for text in FOLLOW_UPS:
        expect(_follow_up(page, text)).to_be_visible()


def test_a_clicked_follow_up_is_sent_and_answered(
    page_for, make_user, upstream, follow_up_generation_on
):
    page = page_for(make_user())
    _asked_answered(page, upstream)
    upstream.queue(reply.text("Dark berries and violets.", match=reply.answering(FOLLOW_UPS[0])))

    _follow_up(page, FOLLOW_UPS[0]).click()

    expect_reply(page, "Dark berries and violets.")
    expect(conversation(page).locator(".chat-user").last).to_contain_text(FOLLOW_UPS[0])
    expect(replies(page)).to_have_count(2)


def test_only_the_last_reply_lists_follow_ups_unless_the_account_keeps_them(
    page_for, make_user, upstream, follow_up_generation_on
):
    plain = page_for(make_user())
    keeping = page_for(_account_with(make_user, keepFollowUpPrompts=True))
    for page in (plain, keeping):
        _asked_answered(page, upstream)
        upstream.queue(reply.text("In late September.", match=reply.answering("next question")))
        send(page, "next question")
        expect_reply(page, "In late September.")

    expect(_follow_up(plain, FOLLOW_UPS[0])).to_have_count(0)
    expect(_follow_up(keeping, FOLLOW_UPS[0])).to_be_visible()


def test_with_insert_to_input_a_click_fills_the_message_box_without_sending(
    page_for, make_user, upstream, follow_up_generation_on
):
    page = page_for(_account_with(make_user, insertFollowUpPrompt=True))
    _asked_answered(page, upstream)
    expect(_follow_up(page, FOLLOW_UPS[1])).to_be_visible()
    requests_before = len(upstream.chat_requests())

    _follow_up(page, FOLLOW_UPS[1]).click()

    expect(chat_input(page)).to_have_text(FOLLOW_UPS[1])
    expect(replies(page)).to_have_count(1)
    assert len(upstream.chat_requests()) == requests_before


def test_an_account_with_follow_ups_off_is_offered_none(
    page_for, make_user, upstream, follow_up_generation_on
):
    page = page_for(_account_with(make_user, autoFollowUps=False))
    upstream.queue(reply.text(ANSWER, match=reply.answering(QUESTION)))
    send(page, QUESTION)
    expect_reply(page, ANSWER)

    page.reload()
    expect_reply(page, ANSWER)
    expect(last_reply(page)).to_be_visible()
    expect(conversation(page).get_by_text("Follow up", exact=True)).to_have_count(0)
    follow_up_requests = [
        body for body in upstream.chat_requests() if reply.answering(FOLLOW_UP_TASK)(body)
    ]
    assert follow_up_requests == []
